insert into Psychiatric_Medication_List (psych_med_idcode, psych_med_generic_name) values (3981530, 'celtis occidentalis pollen');
insert into Psychiatric_Medication_List (psych_med_idcode, psych_med_generic_name) values (8318218, 'polymyxin B sulfate');
insert into Psychiatric_Medication_List (psych_med_idcode, psych_med_generic_name) values (8952699, 'Phenobarbital');
insert into Psychiatric_Medication_List (psych_med_idcode, psych_med_generic_name) values (3259127, 'Green Pea');
insert into Psychiatric_Medication_List (psych_med_idcode, psych_med_generic_name) values (8725898, 'Nedocromil Sodium');
insert into Psychiatric_Medication_List (psych_med_idcode, psych_med_generic_name) values (4487008, 'QUETIAPINE FUMARATE');
insert into Psychiatric_Medication_List (psych_med_idcode, psych_med_generic_name) values (9624956, 'Fluoxetine Hydrochloride');
insert into Psychiatric_Medication_List (psych_med_idcode, psych_med_generic_name) values (5790423, 'Thymus Mercurius');
insert into Psychiatric_Medication_List (psych_med_idcode, psych_med_generic_name) values (2510329, 'Fosphenytoin Sodium');
insert into Psychiatric_Medication_List (psych_med_idcode, psych_med_generic_name) values (7606880, 'Causticum');
insert into Psychiatric_Medication_List (psych_med_idcode, psych_med_generic_name) values (3863888, 'Diphenhydramine HCl');
insert into Psychiatric_Medication_List (psych_med_idcode, psych_med_generic_name) values (2012636, 'Loperamide Hydrochloride');
insert into Psychiatric_Medication_List (psych_med_idcode, psych_med_generic_name) values (3197701, 'Fluoxetine');
insert into Psychiatric_Medication_List (psych_med_idcode, psych_med_generic_name) values (2976347, 'ATRACTYLODES JAPONICA ROOT OIL');
insert into Psychiatric_Medication_List (psych_med_idcode, psych_med_generic_name) values (6724841, 'OCTINOXATE');
insert into Psychiatric_Medication_List (psych_med_idcode, psych_med_generic_name) values (6488509, 'Simethicone');
insert into Psychiatric_Medication_List (psych_med_idcode, psych_med_generic_name) values (7815840, 'GENTAMICIN SULFATE');
insert into Psychiatric_Medication_List (psych_med_idcode, psych_med_generic_name) values (2697958, 'Octinoxate and Oxybenzone');
insert into Psychiatric_Medication_List (psych_med_idcode, psych_med_generic_name) values (9545759, 'Dihydroergotamine Mesylate');
insert into Psychiatric_Medication_List (psych_med_idcode, psych_med_generic_name) values (2513248, 'Hydralazine Hydrochloride');
insert into Psychiatric_Medication_List (psych_med_idcode, psych_med_generic_name) values (5952953, 'Anti Itch Cream');
insert into Psychiatric_Medication_List (psych_med_idcode, psych_med_generic_name) values (3651840, 'Salicylic Acid');
insert into Psychiatric_Medication_List (psych_med_idcode, psych_med_generic_name) values (2213160, 'Titanium Dioxide');
insert into Psychiatric_Medication_List (psych_med_idcode, psych_med_generic_name) values (3940761, 'Ofloxacin');
insert into Psychiatric_Medication_List (psych_med_idcode, psych_med_generic_name) values (4085461, 'Acetaminophen');
insert into Psychiatric_Medication_List (psych_med_idcode, psych_med_generic_name) values (6595960, 'Epidermophyton');
insert into Psychiatric_Medication_List (psych_med_idcode, psych_med_generic_name) values (8984187, 'Azelastine Hydrochloride');
insert into Psychiatric_Medication_List (psych_med_idcode, psych_med_generic_name) values (4243229, 'Glipizide');
insert into Psychiatric_Medication_List (psych_med_idcode, psych_med_generic_name) values (3089016, 'CAFFEINE - CHELIDONIUM MAJUS');
insert into Psychiatric_Medication_List (psych_med_idcode, psych_med_generic_name) values (2965852, 'Triclosan');

